package entity;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA



/**
 * Afdelingen generated by hbm2java
 */
public class Afdelingen  implements java.io.Serializable {


     private String naam;
     private Restaurant restaurant;

    public Afdelingen() {
    }

    public Afdelingen(String naam, Restaurant restaurant) {
       this.naam = naam;
       this.restaurant = restaurant;
    }
   
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }




}


