package entity;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int barCode;
     private Restaurant restaurant;
     private String beschrijving;
     private Double prijs;
     private Set drankjes = new HashSet(0);
     private Set gerechts = new HashSet(0);
     private Set bestellings = new HashSet(0);

    public Product() {
    }

	
    public Product(int barCode, Restaurant restaurant) {
        this.barCode = barCode;
        this.restaurant = restaurant;
    }
    public Product(int barCode, Restaurant restaurant, String beschrijving, Double prijs, Set drankjes, Set gerechts, Set bestellings) {
       this.barCode = barCode;
       this.restaurant = restaurant;
       this.beschrijving = beschrijving;
       this.prijs = prijs;
       this.drankjes = drankjes;
       this.gerechts = gerechts;
       this.bestellings = bestellings;
    }
   
    public int getBarCode() {
        return this.barCode;
    }
    
    public void setBarCode(int barCode) {
        this.barCode = barCode;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    public String getBeschrijving() {
        return this.beschrijving;
    }
    
    public void setBeschrijving(String beschrijving) {
        this.beschrijving = beschrijving;
    }
    public Double getPrijs() {
        return this.prijs;
    }
    
    public void setPrijs(Double prijs) {
        this.prijs = prijs;
    }
    public Set getDrankjes() {
        return this.drankjes;
    }
    
    public void setDrankjes(Set drankjes) {
        this.drankjes = drankjes;
    }
    public Set getGerechts() {
        return this.gerechts;
    }
    
    public void setGerechts(Set gerechts) {
        this.gerechts = gerechts;
    }
    public Set getBestellings() {
        return this.bestellings;
    }
    
    public void setBestellings(Set bestellings) {
        this.bestellings = bestellings;
    }




}


