package dehartigehapbediening.entity.entitys;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bestelling generated by hbm2java
 */
public class Bestelling  implements java.io.Serializable {


     private Integer bestelNr;
     private Rekening rekening;
     private Restaurant restaurant;
     private Tafel tafel;
     private Date datumTijdBestelling;
     private Integer statusCodeDrankjes;
     private Integer statusCodeGerechten;
     private Set products = new HashSet(0);
     private Set plannings = new HashSet(0);

    public Bestelling() {
    }

	
    public Bestelling(Rekening rekening, Restaurant restaurant, Tafel tafel) {
        this.rekening = rekening;
        this.restaurant = restaurant;
        this.tafel = tafel;
    }
    public Bestelling(Rekening rekening, Restaurant restaurant, Tafel tafel, Date datumTijdBestelling, Integer statusCodeDrankjes, Integer statusCodeGerechten, Set products, Set plannings) {
       this.rekening = rekening;
       this.restaurant = restaurant;
       this.tafel = tafel;
       this.datumTijdBestelling = datumTijdBestelling;
       this.statusCodeDrankjes = statusCodeDrankjes;
       this.statusCodeGerechten = statusCodeGerechten;
       this.products = products;
       this.plannings = plannings;
    }
   
    public Integer getBestelNr() {
        return this.bestelNr;
    }
    
    public void setBestelNr(Integer bestelNr) {
        this.bestelNr = bestelNr;
    }
    public Rekening getRekening() {
        return this.rekening;
    }
    
    public void setRekening(Rekening rekening) {
        this.rekening = rekening;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    public Tafel getTafel() {
        return this.tafel;
    }
    
    public void setTafel(Tafel tafel) {
        this.tafel = tafel;
    }
    public Date getDatumTijdBestelling() {
        return this.datumTijdBestelling;
    }
    
    public void setDatumTijdBestelling(Date datumTijdBestelling) {
        this.datumTijdBestelling = datumTijdBestelling;
    }
    public Integer getStatusCodeDrankjes() {
        return this.statusCodeDrankjes;
    }
    
    public void setStatusCodeDrankjes(Integer statusCodeDrankjes) {
        this.statusCodeDrankjes = statusCodeDrankjes;
    }
    public Integer getStatusCodeGerechten() {
        return this.statusCodeGerechten;
    }
    
    public void setStatusCodeGerechten(Integer statusCodeGerechten) {
        this.statusCodeGerechten = statusCodeGerechten;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }
    public Set getPlannings() {
        return this.plannings;
    }
    
    public void setPlannings(Set plannings) {
        this.plannings = plannings;
    }




}


