package dehartigehapbediening.entity.entitys;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA



/**
 * Gebruikers generated by hbm2java
 */
public class Gebruikers  implements java.io.Serializable {


     private Integer gebruikersNr;
     private String gebruikersNaam;
     private String wachtwoord;
     private String afdelingenNaam;

    public Gebruikers() {
    }

	
    public Gebruikers(String afdelingenNaam) {
        this.afdelingenNaam = afdelingenNaam;
    }
    public Gebruikers(String gebruikersNaam, String wachtwoord, String afdelingenNaam) {
       this.gebruikersNaam = gebruikersNaam;
       this.wachtwoord = wachtwoord;
       this.afdelingenNaam = afdelingenNaam;
    }
   
    public Integer getGebruikersNr() {
        return this.gebruikersNr;
    }
    
    public void setGebruikersNr(Integer gebruikersNr) {
        this.gebruikersNr = gebruikersNr;
    }
    public String getGebruikersNaam() {
        return this.gebruikersNaam;
    }
    
    public void setGebruikersNaam(String gebruikersNaam) {
        this.gebruikersNaam = gebruikersNaam;
    }
    public String getWachtwoord() {
        return this.wachtwoord;
    }
    
    public void setWachtwoord(String wachtwoord) {
        this.wachtwoord = wachtwoord;
    }
    public String getAfdelingenNaam() {
        return this.afdelingenNaam;
    }
    
    public void setAfdelingenNaam(String afdelingenNaam) {
        this.afdelingenNaam = afdelingenNaam;
    }




}


