package dehartigehapbediening.entity.entitys;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ingredient generated by hbm2java
 */
public class Ingredient  implements java.io.Serializable {


     private int ingredient;
     private Restaurant restaurant;
     private String naam;
     private Set gerechts = new HashSet(0);

    public Ingredient() {
    }

	
    public Ingredient(int ingredient, Restaurant restaurant) {
        this.ingredient = ingredient;
        this.restaurant = restaurant;
    }
    public Ingredient(int ingredient, Restaurant restaurant, String naam, Set gerechts) {
       this.ingredient = ingredient;
       this.restaurant = restaurant;
       this.naam = naam;
       this.gerechts = gerechts;
    }
   
    public int getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(int ingredient) {
        this.ingredient = ingredient;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Set getGerechts() {
        return this.gerechts;
    }
    
    public void setGerechts(Set gerechts) {
        this.gerechts = gerechts;
    }




}


