package dehartigehapbediening.entity.entitys;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Planning generated by hbm2java
 */
public class Planning  implements java.io.Serializable {


     private int bestellingBestelNr;
     private Bestelling bestelling;
     private Date beginTijd;
     private Date eindTijd;
     private String commentaar;

    public Planning() {
    }

	
    public Planning(int bestellingBestelNr, Bestelling bestelling) {
        this.bestellingBestelNr = bestellingBestelNr;
        this.bestelling = bestelling;
    }
    public Planning(int bestellingBestelNr, Bestelling bestelling, Date beginTijd, Date eindTijd, String commentaar) {
       this.bestellingBestelNr = bestellingBestelNr;
       this.bestelling = bestelling;
       this.beginTijd = beginTijd;
       this.eindTijd = eindTijd;
       this.commentaar = commentaar;
    }
   
    public int getBestellingBestelNr() {
        return this.bestellingBestelNr;
    }
    
    public void setBestellingBestelNr(int bestellingBestelNr) {
        this.bestellingBestelNr = bestellingBestelNr;
    }
    public Bestelling getBestelling() {
        return this.bestelling;
    }
    
    public void setBestelling(Bestelling bestelling) {
        this.bestelling = bestelling;
    }
    public Date getBeginTijd() {
        return this.beginTijd;
    }
    
    public void setBeginTijd(Date beginTijd) {
        this.beginTijd = beginTijd;
    }
    public Date getEindTijd() {
        return this.eindTijd;
    }
    
    public void setEindTijd(Date eindTijd) {
        this.eindTijd = eindTijd;
    }
    public String getCommentaar() {
        return this.commentaar;
    }
    
    public void setCommentaar(String commentaar) {
        this.commentaar = commentaar;
    }




}


