package dehartigehapbediening.entity.entitys;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant  implements java.io.Serializable {


     private String naam;
     private Set products = new HashSet(0);
     private Set tafels = new HashSet(0);
     private Set rekenings = new HashSet(0);
     private Set afdelingens = new HashSet(0);
     private Set bestellings = new HashSet(0);
     private Set ingredients = new HashSet(0);

    public Restaurant() {
    }

	
    public Restaurant(String naam) {
        this.naam = naam;
    }
    public Restaurant(String naam, Set products, Set tafels, Set rekenings, Set afdelingens, Set bestellings, Set ingredients) {
       this.naam = naam;
       this.products = products;
       this.tafels = tafels;
       this.rekenings = rekenings;
       this.afdelingens = afdelingens;
       this.bestellings = bestellings;
       this.ingredients = ingredients;
    }
   
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }
    public Set getTafels() {
        return this.tafels;
    }
    
    public void setTafels(Set tafels) {
        this.tafels = tafels;
    }
    public Set getRekenings() {
        return this.rekenings;
    }
    
    public void setRekenings(Set rekenings) {
        this.rekenings = rekenings;
    }
    public Set getAfdelingens() {
        return this.afdelingens;
    }
    
    public void setAfdelingens(Set afdelingens) {
        this.afdelingens = afdelingens;
    }
    public Set getBestellings() {
        return this.bestellings;
    }
    
    public void setBestellings(Set bestellings) {
        this.bestellings = bestellings;
    }
    public Set getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(Set ingredients) {
        this.ingredients = ingredients;
    }




}


