package dehartigehapbediening.entity.entitys;
// Generated Nov 22, 2011 3:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tafel generated by hbm2java
 */
public class Tafel  implements java.io.Serializable {


     private int tafelNr;
     private Restaurant restaurant;
     private Set rekenings = new HashSet(0);
     private Set bestellings = new HashSet(0);

    public Tafel() {
    }

	
    public Tafel(int tafelNr, Restaurant restaurant) {
        this.tafelNr = tafelNr;
        this.restaurant = restaurant;
    }
    public Tafel(int tafelNr, Restaurant restaurant, Set rekenings, Set bestellings) {
       this.tafelNr = tafelNr;
       this.restaurant = restaurant;
       this.rekenings = rekenings;
       this.bestellings = bestellings;
    }
   
    public int getTafelNr() {
        return this.tafelNr;
    }
    
    public void setTafelNr(int tafelNr) {
        this.tafelNr = tafelNr;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    public Set getRekenings() {
        return this.rekenings;
    }
    
    public void setRekenings(Set rekenings) {
        this.rekenings = rekenings;
    }
    public Set getBestellings() {
        return this.bestellings;
    }
    
    public void setBestellings(Set bestellings) {
        this.bestellings = bestellings;
    }




}


